//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.26 at 09:01:51 PM MSK 
//


package com.xokker;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.xokker package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.xokker
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Customers }
     * 
     */
    public Customers createCustomers() {
        return new Customers();
    }

    /**
     * Create an instance of {@link Customers.Customer }
     * 
     */
    public Customers.Customer createCustomersCustomer() {
        return new Customers.Customer();
    }

    /**
     * Create an instance of {@link Customers.Customer.Orders }
     * 
     */
    public Customers.Customer.Orders createCustomersCustomerOrders() {
        return new Customers.Customer.Orders();
    }

    /**
     * Create an instance of {@link Customers.Customer.Orders.Order }
     * 
     */
    public Customers.Customer.Orders.Order createCustomersCustomerOrdersOrder() {
        return new Customers.Customer.Orders.Order();
    }

    /**
     * Create an instance of {@link Customers.Customer.Orders.Order.Positions }
     * 
     */
    public Customers.Customer.Orders.Order.Positions createCustomersCustomerOrdersOrderPositions() {
        return new Customers.Customer.Orders.Order.Positions();
    }

    /**
     * Create an instance of {@link Customers.Customer.Orders.Order.Positions.Position }
     * 
     */
    public Customers.Customer.Orders.Order.Positions.Position createCustomersCustomerOrdersOrderPositionsPosition() {
        return new Customers.Customer.Orders.Order.Positions.Position();
    }

}
